
  const SHOW_EDIT_MODAL='SHOW_EDIT_MODAL';
  const HIDE_EDIT_MODAL='HIDE_EDIT_MODAL';
  const SHOW_UPLOAD_MODAL='SHOW_UPLOAD_MODAL';
  const HIDE_UPLODAD_MODAL='HIDE_UPLOAD_MODAL';
  const DEFAULT_BUTTON={type:'primary',size:'mini'};

export{
  SHOW_EDIT_MODAL,
  HIDE_EDIT_MODAL,
  SHOW_UPLOAD_MODAL,
  HIDE_UPLODAD_MODAL,
  DEFAULT_BUTTON
}